# Generated by Django 4.0.4 on 2022-05-21 19:51

import arch.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='model name')),
                ('area', models.FloatField(default=0.0)),
                ('floors', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('size', models.IntegerField(choices=[(1, 'tiny'), (2, 'medium'), (3, 'large')], help_text='Select house size', verbose_name='House size')),
                ('roof', models.IntegerField(choices=[(1, 'pitched'), (2, 'flat'), (3, 'combined')], help_text='Select roof type', null=True, verbose_name='Roof type')),
                ('entrance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Select the number of entrances', verbose_name='Number of entrances')),
                ('bedroom', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Select the number of bedrooms', verbose_name='Number of bedrooms')),
                ('bathroom', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Select the number of bathrooms', verbose_name='Number of bathrooms')),
                ('kitchen_living_room', models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Kitchen connected to living room')),
                ('tech_room', models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a technical room')),
                ('laundry', models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a laundry')),
                ('terrace', models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a terrace')),
                ('fireplace', models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a fireplace')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input material type', max_length=30, verbose_name='Material type')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input architectural style', max_length=30, verbose_name='Architectural style')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=arch.models.Image.path_rename)),
                ('house', models.ForeignKey(help_text='Please attach images', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.house', verbose_name='House')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='material',
            field=models.ForeignKey(help_text='Select material type', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.material', verbose_name='Material type'),
        ),
        migrations.AddField(
            model_name='house',
            name='style',
            field=models.ForeignKey(help_text='Select architectural style', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.style', verbose_name='Architectural style'),
        ),
    ]
