# Generated by Django 4.0.4 on 2022-08-11 14:11

import arch.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True, verbose_name='Model name')),
                ('area', models.FloatField(default=0.0)),
                ('floors', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Floors')),
                ('entrance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Number of entrances')),
                ('bedroom', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Number of bedrooms')),
                ('bathroom', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Number of bathrooms')),
                ('kitchen_living_room', models.BooleanField(default=True, verbose_name='Kitchen connected to living room')),
                ('tech_room', models.BooleanField(default=True, verbose_name='Does house have a  technical room')),
                ('terrace', models.BooleanField(default=False, verbose_name='Does house have a  terrace')),
                ('garage', models.BooleanField(default=False, verbose_name='Does house have a  garage')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input material type', max_length=30, verbose_name='Material type')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input roof type', max_length=30, verbose_name='Roof type')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input architectural style', max_length=30, verbose_name='Architectural style')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ImageField(blank=True, null=True, upload_to=arch.models.PathRename('plan', 'plans', 'plan'))),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(help_text='Please attach drawings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='arch.house', verbose_name='HousePage')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, null=True, upload_to=arch.models.PathRename('original', 'images', 'image'))),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=arch.models.PathRename('thumbnail', 'images/thumbnails', 'thumb'))),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(help_text='Please attach images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='arch.house', verbose_name='HousePage')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.material', verbose_name='Material type'),
        ),
        migrations.AddField(
            model_name='house',
            name='roof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.roof', verbose_name='Roof type'),
        ),
        migrations.AddField(
            model_name='house',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.style', verbose_name='Architectural style'),
        ),
    ]
