# Generated by Django 4.0.2 on 2022-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='floors',
            field=models.IntegerField(default=1),
        ),
    ]
