# Generated by Django 4.0.4 on 2022-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
