# Generated by Django 4.0.4 on 2022-07-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='size',
        ),
    ]
