# Generated by Django 4.0.4 on 2022-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0002_image_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='garage',
            field=models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a garage'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_living_room',
            field=models.BooleanField(default=True, help_text='Check the box if yes', verbose_name='Kitchen connected to living room'),
        ),
        migrations.AlterField(
            model_name='house',
            name='tech_room',
            field=models.BooleanField(default=True, help_text='Check the box if yes', verbose_name='Is there a technical room'),
        ),
    ]
