# Generated by Django 4.0.2 on 2022-02-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0002_house_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(choices=[(1, 'one-story'), (2, 'two-storied'), (3, 'three-storey'), (4, 'four-storey')], default=1),
        ),
    ]
