# Generated by Django 4.0.4 on 2022-06-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0002_remove_drawing_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='house',
            field=models.ForeignKey(help_text='Please attach drawings', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.house', verbose_name='House'),
        ),
    ]
