# Generated by Django 4.0.4 on 2022-07-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0002_remove_house_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input roof type', max_length=30, verbose_name='Roof type')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='roof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.roof', verbose_name='Roof type'),
        ),
    ]
