# Generated by Django 4.0.2 on 2022-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0003_alter_house_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='size',
            field=models.CharField(blank=True, choices=[(1, 'tiny'), (2, 'medium'), (3, 'large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
