# Generated by Django 4.0.4 on 2022-07-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0003_roof_alter_house_roof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='fireplace',
        ),
        migrations.RemoveField(
            model_name='house',
            name='laundry',
        ),
        migrations.AlterField(
            model_name='house',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Does house have a... garage'),
        ),
        migrations.AlterField(
            model_name='house',
            name='tech_room',
            field=models.BooleanField(default=True, verbose_name='Does house have a... technical room'),
        ),
        migrations.AlterField(
            model_name='house',
            name='terrace',
            field=models.BooleanField(default=False, verbose_name='Does house have a... terrace'),
        ),
    ]
