# Generated by Django 4.0.2 on 2022-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0004_house_size_alter_house_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'tiny'), (2, 'medium'), (3, 'large')], max_length=10),
        ),
    ]
