# Generated by Django 4.0.2 on 2022-03-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0005_alter_house_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input matetial type', max_length=30, verbose_name='Material type')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input architectural style', max_length=30, verbose_name='Architectural style')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='roof',
            field=models.IntegerField(choices=[(1, 'pitched'), (2, 'flat')], help_text='Choose roof type', null=True, verbose_name='Roof type'),
        ),
        migrations.AlterField(
            model_name='house',
            name='size',
            field=models.IntegerField(choices=[(1, 'tiny'), (2, 'medium'), (3, 'large')], help_text='Choose house size', verbose_name='House size'),
        ),
        migrations.AddField(
            model_name='house',
            name='material',
            field=models.ForeignKey(help_text='Choose material type', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.material', verbose_name='Material type'),
        ),
        migrations.AddField(
            model_name='house',
            name='style',
            field=models.ForeignKey(help_text='Choose architectural style', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.style', verbose_name='Architectural style'),
        ),
    ]
