# Generated by Django 4.0.2 on 2022-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0007_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='entrance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
