# Generated by Django 4.0.2 on 2022-05-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0008_house_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Select the number of bedrooms', verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='entrance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Select the number of entrances', verbose_name='Number of entrances'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='material',
            field=models.ForeignKey(help_text='Select material type', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.material', verbose_name='Material type'),
        ),
        migrations.AlterField(
            model_name='house',
            name='roof',
            field=models.IntegerField(choices=[(1, 'pitched'), (2, 'flat')], help_text='Select roof type', null=True, verbose_name='Roof type'),
        ),
        migrations.AlterField(
            model_name='house',
            name='size',
            field=models.IntegerField(choices=[(1, 'tiny'), (2, 'medium'), (3, 'large')], help_text='Select house size', verbose_name='House size'),
        ),
        migrations.AlterField(
            model_name='house',
            name='style',
            field=models.ForeignKey(help_text='Select architectural style', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.style', verbose_name='Architectural style'),
        ),
    ]
