# Generated by Django 4.0.2 on 2022-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0009_house_bedroom_alter_house_entrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Select the number of bathrooms', verbose_name='Number of bathrooms'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_living_room',
            field=models.BooleanField(default=False, help_text='Kitchen connected to living room?', verbose_name='kitchen and living room'),
        ),
        migrations.AlterField(
            model_name='house',
            name='entrance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Select the number of entrances', verbose_name='Number of entrances'),
        ),
    ]
