# Generated by Django 4.0.2 on 2022-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0010_house_bathroom_house_kitchen_living_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='fireplace',
            field=models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a fireplace'),
        ),
        migrations.AddField(
            model_name='house',
            name='laundry',
            field=models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a laundry'),
        ),
        migrations.AddField(
            model_name='house',
            name='tech_room',
            field=models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a technical room'),
        ),
        migrations.AddField(
            model_name='house',
            name='terrace',
            field=models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Is there a terrace'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_living_room',
            field=models.BooleanField(default=False, help_text='Check the box if yes', verbose_name='Kitchen connected to living room'),
        ),
    ]
